/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.awt.Window;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import model.entity.ChatBubble;
import model.entity.OnlineUser;

/**
 *
 * @author Ken
 */
public class ChatFrm extends javax.swing.JFrame {
    private OnlineUser chatWith;
    private DefaultListModel<ChatBubble> model;
    /**
     * Creates new form ChatFrm
     * @param chatWith
     */
    public ChatFrm(OnlineUser chatWith) {
        setTitle("Chat with " + chatWith.getUsername());
        initComponents();
        setDefaultCloseOperation(1);
        this.chatWith = chatWith;
        model = new DefaultListModel<>();
        listMessages.setModel(model);
        listMessages.setCellRenderer(new ChatBubbleRenderer());
        txtChatInput.requestFocus();
        setLocationRelativeTo(null);
    }

    public String getChatInput() {
        return txtChatInput.getText();
    }
    
    public void resetChatInput() {
        txtChatInput.setText("");
    }
    
    public void appendMsg(ChatBubble chatBubble) {
        model.addElement(chatBubble);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrListMessages = new javax.swing.JScrollPane();
        listMessages = new javax.swing.JList();
        txtChatInput = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        listMessages.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrListMessages.setViewportView(listMessages);

        btnSend.setText("Send");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrListMessages)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtChatInput, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnSend)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrListMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChatInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSend))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JList listMessages;
    private javax.swing.JScrollPane scrListMessages;
    private javax.swing.JTextField txtChatInput;
    // End of variables declaration//GEN-END:variables

    public ImageIcon getAvatar() {
        return chatWith.getAvatar();
    }

    public JButton getBtnSend() {
        return btnSend;
    }
}
