/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Component;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import model.entity.OnlineUser;

/**
 *
 * @author Ken
 */
public class OnlineUserRenderer extends javax.swing.JPanel implements ListCellRenderer<OnlineUser> {

    /**
     * Creates new form OnlineUserRenderer
     */
    public OnlineUserRenderer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvatar = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));

        lblAvatar.setText("avatar");
        lblAvatar.setMaximumSize(new java.awt.Dimension(60, 60));
        lblAvatar.setMinimumSize(new java.awt.Dimension(60, 60));
        lblAvatar.setPreferredSize(new java.awt.Dimension(60, 60));

        lblUsername.setText("username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsername)
                .addGap(0, 204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsername))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends OnlineUser> list,
            OnlineUser onlineUser, int index, boolean isSelected, boolean cellHasFocus) {
        Image img = onlineUser.getAvatar().getImage();
        ImageIcon avatar = new ImageIcon(img.getScaledInstance(55, 55, Image.SCALE_SMOOTH));
        lblAvatar.setIcon(avatar);
        lblUsername.setText(onlineUser.getUsername());

        // set Opaque to change background color of JLabel
        lblUsername.setOpaque(true);

        // when select item
        if (isSelected) {
            lblUsername.setBackground(list.getSelectionBackground());
            setBackground(list.getSelectionBackground());
        } else { // when don't select
            lblUsername.setBackground(list.getBackground());
            setBackground(list.getBackground());
        }
        return this;
    }
}
